data_set_names = ["Adressa-One-Week", "Alibaba-IFashion", "Alibaba-Mobile", "Amazon-MP3", "Amazon-Ratings",
                  "Amazon2014-Amazon-Instant-Video", "Amazon2014-Apps-For-Android", "Amazon2014-Automotive",
                  "Amazon2014-Baby", "Amazon2014-Beauty", "Amazon2014-Books", "Amazon2014-CDs-And-Vinyl",
                  "Amazon2014-Cell-Phones-And-Accessories", "Amazon2014-Clothing-Shoes-And-Jewelry",
                  "Amazon2014-Digital-Music", "Amazon2014-Electronics", "Amazon2014-Grocery-And-Gourmet",
                  "Amazon2014-Health-And-Personal-Care", "Amazon2014-Home-And-Kitchen", "Amazon2014-Kindle-Store",
                  "Amazon2014-Movies-And-TV", "Amazon2014-Musical-Instruments", "Amazon2014-Office-Products",
                  "Amazon2014-Patio-Lawn-And-Garden", "Amazon2014-Pet-Supplies", "Amazon2014-Sports-And-Outdoors",
                  "Amazon2014-Tools-And-Home-Improvement", "Amazon2014-Toys-And-Games", "Amazon2014-Video-Games",
                  "Amazon2018-All-Beauty", "Amazon2018-Appliances", "Amazon2018-Arts-Crafts-And-Sewing",
                  "Amazon2018-Automotive", "Amazon2018-Books", "Amazon2018-CDs-And-Vinyl",
                  "Amazon2018-Cell-Phones-And-Accessories", "Amazon2018-Clothing-Shoes-And-Jewelry",
                  "Amazon2018-Digital-Music", "Amazon2018-Electronics", "Amazon2018-Fashion", "Amazon2018-Gift-Cards",
                  "Amazon2018-Grocery-And-Gourmet-Food", "Amazon2018-Home-And-Kitchen",
                  "Amazon2018-Industrial-And-Scientific", "Amazon2018-Kindle-Store", "Amazon2018-Luxury-Beauty",
                  "Amazon2018-Magazine-Subscriptions", "Amazon2018-Movies-And-TV", "Amazon2018-Musical-Instruments",
                  "Amazon2018-Office-Products", "Amazon2018-Patio-Lawn-And-Garden", "Amazon2018-Pet-Supplies",
                  "Amazon2018-Prime-Pantry", "Amazon2018-Software", "Amazon2018-Sports-And-Outdoors",
                  "Amazon2018-Tools-And-Home-Improvement", "Amazon2018-Toys-And-Games", "Amazon2018-Video-Games",
                  "Anime", "BeerAdvocate", "Behance", "BookCrossing", "CiaoDVD", "CiteULike-A", "CiteULike-T",
                  "ContentWise-Impressions", "CosmeticsShop", "DeliveryHero-SE", "DeliveryHero-SG", "DeliveryHero-TW",
                  "Dianping-SequentialRec", "Dianping-SocialRec", "Digg", "Diginetica", "Docear-Mind-Maps",
                  "Docear-Recommendations", "Douban-Book", "Douban-Movie", "Douban-Music", "Douban-Short", "Dunnhumby",
                  "EachMovie", "EchoNest", "EndoMondo", "Epinions", "Epinions-Extended", "Epinions-Social", "Escorts",
                  "FilmTrust", "FoodComRecipes", "Foursquare-Global1", "Foursquare-Global2", "Foursquare-NYC1",
                  "Foursquare-NYC2", "Foursquare-Tokyo", "Frappe", "Globo", "Goodreads-Children",
                  "Goodreads-Comics-And-Graphic", "Goodreads-Fantasy-And-Paranormal", "Goodreads-History-And-Biography",
                  "Goodreads-Mystery-Thriller-And-Crime", "Goodreads-Poetry", "Goodreads-Romance",
                  "Goodreads-Young-Adult", "GoogleLocal2018", "GoogleLocal2021-Alabama", "GoogleLocal2021-Alaska",
                  "GoogleLocal2021-Arizona", "GoogleLocal2021-Arkansas", "GoogleLocal2021-California",
                  "GoogleLocal2021-Colorado", "GoogleLocal2021-Connecticut", "GoogleLocal2021-Delaware",
                  "GoogleLocal2021-District-Of-Columbia", "GoogleLocal2021-Florida", "GoogleLocal2021-Georgia",
                  "GoogleLocal2021-Hawaii", "GoogleLocal2021-Idaho", "GoogleLocal2021-Illinois",
                  "GoogleLocal2021-Indiana", "GoogleLocal2021-Iowa", "GoogleLocal2021-Kansas",
                  "GoogleLocal2021-Kentucky", "GoogleLocal2021-Louisiana", "GoogleLocal2021-Maine",
                  "GoogleLocal2021-Maryland", "GoogleLocal2021-Massachusetts", "GoogleLocal2021-Michigan",
                  "GoogleLocal2021-Minnesota", "GoogleLocal2021-Mississippi", "GoogleLocal2021-Missouri",
                  "GoogleLocal2021-Montana", "GoogleLocal2021-Nebraska", "GoogleLocal2021-Nevada",
                  "GoogleLocal2021-New-Hampshire", "GoogleLocal2021-New-Jersey", "GoogleLocal2021-New-Mexico",
                  "GoogleLocal2021-New-York", "GoogleLocal2021-North-Carolina", "GoogleLocal2021-North-Dakota",
                  "GoogleLocal2021-Ohio", "GoogleLocal2021-Oklahoma", "GoogleLocal2021-Oregon",
                  "GoogleLocal2021-Pennsylvania", "GoogleLocal2021-Rhode-Island", "GoogleLocal2021-South-Carolina",
                  "GoogleLocal2021-South-Dakota", "GoogleLocal2021-Tennessee", "GoogleLocal2021-Texas",
                  "GoogleLocal2021-Utah", "GoogleLocal2021-Vermont", "GoogleLocal2021-Virginia",
                  "GoogleLocal2021-Washington", "GoogleLocal2021-West-Virginia", "GoogleLocal2021-Wisconsin",
                  "GoogleLocal2021-Wyoming", "Gowalla", "Hetrec-Delicious", "Hetrec-LastFM", "InCarMusic", "InstaCart",
                  "IPinYou", "Jester-1", "Jester-2", "Jester-2Plus", "Jester-3", "Jester-4", "KGRec-Music",
                  "KGRec-Sound", "LastFM-1B", "LastFM-1K", "LastFM-360K", "LearningFromSets", "Libimseti",
                  "Librarything", "MarketBias-Electronics", "MarketBias-ModCloth", "MIND-Large", "MIND-Small",
                  "ModCloth-Clothing-Fit", "MovieLens-100K", "MovieLens-10M", "MovieLens-1B-Synthetic", "MovieLens-1M",
                  "MovieLens-20M", "MovieLens-25M", "MovieLens-Latest", "MovieLens-Latest-Small", "MovieTweetings",
                  "Music4All-Onion", "Myket-Android", "Netflix", "Nowplaying-RS", "Personality", "Pinterest", "RARD-II",
                  "RateBeer", "RatingDisposition", "Reddit", "Rekko", "RentTheRunway", "Retailrocket", "Serendipity",
                  "Sketchfab", "SpotifyPlaylists", "StackOverflow", "Steam-Australian-Libraries",
                  "Steam-Australian-Reviews", "Steam-Recommendations", "Steam-Reviews", "TaFeng", "Taobao-AdClick",
                  "Taobao-UserBehavior", "ThirtyMusic", "Tmall", "TripAdvisor", "TV-Audience", "Twitch-100K",
                  "Twitch-Full", "WikiLens", "Yahoo-Movies", "Yahoo-Music1", "Yahoo-Music2", "Yahoo-Music3",
                  "Yahoo-Semi-Synthetic", "Yahoo-Songs", "Yelp-2018", "Yelp-2019", "Yelp-2020", "Yelp-2021",
                  "Yelp-2022", "Yelp-2023", "Yoochoose"]

available_data_set_names = ["Adressa-One-Week", "Alibaba-IFashion", "Alibaba-Mobile", "Amazon-MP3", "Amazon-Ratings",
                            "Amazon2014-Amazon-Instant-Video", "Amazon2014-Apps-For-Android", "Amazon2014-Automotive",
                            "Amazon2014-Baby", "Amazon2014-Beauty", "Amazon2014-Books", "Amazon2014-CDs-And-Vinyl",
                            "Amazon2014-Cell-Phones-And-Accessories", "Amazon2014-Clothing-Shoes-And-Jewelry",
                            "Amazon2014-Digital-Music", "Amazon2014-Electronics", "Amazon2014-Grocery-And-Gourmet",
                            "Amazon2014-Health-And-Personal-Care", "Amazon2014-Home-And-Kitchen",
                            "Amazon2014-Kindle-Store", "Amazon2014-Movies-And-TV", "Amazon2014-Musical-Instruments",
                            "Amazon2014-Office-Products", "Amazon2014-Patio-Lawn-And-Garden", "Amazon2014-Pet-Supplies",
                            "Amazon2014-Sports-And-Outdoors", "Amazon2014-Tools-And-Home-Improvement",
                            "Amazon2014-Toys-And-Games", "Amazon2014-Video-Games", "Amazon2018-All-Beauty",
                            "Amazon2018-Appliances", "Amazon2018-Arts-Crafts-And-Sewing", "Amazon2018-Automotive",
                            "Amazon2018-Books", "Amazon2018-CDs-And-Vinyl", "Amazon2018-Cell-Phones-And-Accessories",
                            "Amazon2018-Clothing-Shoes-And-Jewelry", "Amazon2018-Digital-Music",
                            "Amazon2018-Electronics", "Amazon2018-Fashion", "Amazon2018-Gift-Cards",
                            "Amazon2018-Grocery-And-Gourmet-Food", "Amazon2018-Home-And-Kitchen",
                            "Amazon2018-Industrial-And-Scientific", "Amazon2018-Kindle-Store",
                            "Amazon2018-Luxury-Beauty", "Amazon2018-Magazine-Subscriptions", "Amazon2018-Movies-And-TV",
                            "Amazon2018-Musical-Instruments", "Amazon2018-Office-Products",
                            "Amazon2018-Patio-Lawn-And-Garden", "Amazon2018-Pet-Supplies", "Amazon2018-Prime-Pantry",
                            "Amazon2018-Software", "Amazon2018-Sports-And-Outdoors",
                            "Amazon2018-Tools-And-Home-Improvement", "Amazon2018-Toys-And-Games",
                            "Amazon2018-Video-Games", "Anime", "BeerAdvocate", "Behance", "BookCrossing", "CiaoDVD",
                            "CiteULike-A", "CiteULike-T", "ContentWise-Impressions", "CosmeticsShop", "DeliveryHero-SE",
                            "DeliveryHero-SG", "DeliveryHero-TW", "Dianping-SequentialRec", "Dianping-SocialRec",
                            "Digg", "Diginetica", "Docear-Mind-Maps", "Docear-Recommendations", "Douban-Book",
                            "Douban-Movie", "Douban-Music", "Douban-Short", "Dunnhumby", "EachMovie", "EchoNest",
                            "EndoMondo", "Epinions", "Epinions-Extended", "Epinions-Social", "Escorts", "FilmTrust",
                            "FoodComRecipes", "Foursquare-Global1", "Foursquare-Global2", "Foursquare-NYC1",
                            "Foursquare-NYC2", "Foursquare-Tokyo", "Frappe", "Globo", "Goodreads-Children",
                            "Goodreads-Comics-And-Graphic", "Goodreads-Fantasy-And-Paranormal",
                            "Goodreads-History-And-Biography", "Goodreads-Mystery-Thriller-And-Crime",
                            "Goodreads-Poetry", "Goodreads-Romance", "Goodreads-Young-Adult", "GoogleLocal2018",
                            "GoogleLocal2021-Alabama", "GoogleLocal2021-Alaska", "GoogleLocal2021-Arizona",
                            "GoogleLocal2021-Arkansas", "GoogleLocal2021-California", "GoogleLocal2021-Colorado",
                            "GoogleLocal2021-Connecticut", "GoogleLocal2021-Delaware",
                            "GoogleLocal2021-District-Of-Columbia", "GoogleLocal2021-Florida",
                            "GoogleLocal2021-Georgia", "GoogleLocal2021-Hawaii", "GoogleLocal2021-Idaho",
                            "GoogleLocal2021-Illinois", "GoogleLocal2021-Indiana", "GoogleLocal2021-Iowa",
                            "GoogleLocal2021-Kansas", "GoogleLocal2021-Kentucky", "GoogleLocal2021-Louisiana",
                            "GoogleLocal2021-Maine", "GoogleLocal2021-Maryland", "GoogleLocal2021-Massachusetts",
                            "GoogleLocal2021-Michigan", "GoogleLocal2021-Minnesota", "GoogleLocal2021-Mississippi",
                            "GoogleLocal2021-Missouri", "GoogleLocal2021-Montana", "GoogleLocal2021-Nebraska",
                            "GoogleLocal2021-Nevada", "GoogleLocal2021-New-Hampshire", "GoogleLocal2021-New-Jersey",
                            "GoogleLocal2021-New-Mexico", "GoogleLocal2021-New-York", "GoogleLocal2021-North-Carolina",
                            "GoogleLocal2021-North-Dakota", "GoogleLocal2021-Ohio", "GoogleLocal2021-Oklahoma",
                            "GoogleLocal2021-Oregon", "GoogleLocal2021-Pennsylvania", "GoogleLocal2021-Rhode-Island",
                            "GoogleLocal2021-South-Carolina", "GoogleLocal2021-South-Dakota",
                            "GoogleLocal2021-Tennessee", "GoogleLocal2021-Texas", "GoogleLocal2021-Utah",
                            "GoogleLocal2021-Vermont", "GoogleLocal2021-Virginia", "GoogleLocal2021-Washington",
                            "GoogleLocal2021-West-Virginia", "GoogleLocal2021-Wisconsin", "GoogleLocal2021-Wyoming",
                            "Gowalla", "Hetrec-Delicious", "Hetrec-LastFM", "InCarMusic", "InstaCart", "IPinYou",
                            "Jester-1", "Jester-2", "Jester-2Plus", "Jester-3", "Jester-4", "KGRec-Music",
                            "KGRec-Sound", "LastFM-1B", "LastFM-1K", "LastFM-360K", "LearningFromSets", "Libimseti",
                            "Librarything", "MarketBias-Electronics", "MarketBias-ModCloth", "MIND-Large", "MIND-Small",
                            "ModCloth-Clothing-Fit", "MovieLens-100K", "MovieLens-10M", "MovieLens-1B-Synthetic",
                            "MovieLens-1M", "MovieLens-20M", "MovieLens-25M", "MovieLens-Latest",
                            "MovieLens-Latest-Small", "MovieTweetings", "Music4All-Onion", "Myket-Android", "Netflix",
                            "Nowplaying-RS", "Personality", "Pinterest", "RARD-II", "RateBeer", "RatingDisposition",
                            "Reddit", "Rekko", "RentTheRunway", "Retailrocket", "Serendipity", "Sketchfab",
                            "SpotifyPlaylists", "StackOverflow", "Steam-Australian-Libraries",
                            "Steam-Australian-Reviews", "Steam-Recommendations", "Steam-Reviews", "TaFeng",
                            "Taobao-AdClick", "Taobao-UserBehavior", "ThirtyMusic", "Tmall", "TripAdvisor",
                            "TV-Audience", "Twitch-100K", "Twitch-Full", "WikiLens", "Yahoo-Movies", "Yahoo-Music1",
                            "Yahoo-Music2", "Yahoo-Music3", "Yahoo-Semi-Synthetic", "Yahoo-Songs", "Yelp-2018",
                            "Yelp-2019", "Yelp-2020", "Yelp-2021", "Yelp-2022", "Yelp-2023", "Yoochoose"]
